

name: Build .deb - Ubuntu 20

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Build .deb file
      run: cargo deb
    - uses: actions/upload-artifact@v3
      with:
        name: .Deb
        path: target/debian/wineget_1.2.0_amd64.deb
